In [1]:
import numpy as np
import random

In [2]:
t1 = np.array([1, 2, 3,])
print(t1)
print(type(t1))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
t2 = np.array(range(12))
print(t2)
t2.dtype

[ 0  1  2  3  4  5  6  7  8  9 10 11]


dtype('int32')

t3 = np.arange(12)

In [4]:
t3 = np.arange(12)   # 快速生成从0 到 12 的数字
t3.dtype

dtype('int32')

In [5]:
t4 = np.array(range(1, 10), dtype = "i1")
print(t4)
t4.dtype

[1 2 3 4 5 6 7 8 9]


dtype('int8')

In [6]:
# numpy中的bool类型
t5 = np.array([1, 0, 1, 0, 0, 1], dtype = bool)
print(t5)
t5.dtype

[ True False  True False False  True]


dtype('bool')

In [7]:
#调整数据类型
t6 = t5.astype("int8")
t6

array([1, 0, 1, 0, 0, 1], dtype=int8)

In [8]:
t7 = np.array([random.random() for i in range(10)])
print(t7)
matrix = [i for i in range(10)]
print(matrix)

t8 = np.round(t7, 2)
print(t8)


[0.64072221 0.81647881 0.75115636 0.4515972  0.66323522 0.28185491
 0.08986404 0.96665054 0.55706402 0.98804574]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0.64 0.82 0.75 0.45 0.66 0.28 0.09 0.97 0.56 0.99]


In [9]:
s1 = np.arange(12)
print(s1.shape)
print(s1.reshape((3, 4)))

(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
s2 = np.array([[1, 2, 3], [2, 3, 4]])
s2.shape

(2, 3)

In [11]:
s3 = np.array([[[0, 2, 3], [2, 3, 4]], [[1, 2, 3], [2, 3, 4]]])
s3.shape

(2, 2, 3)

In [12]:
s3 = s3.reshape((4, 3))
s3

array([[0, 2, 3],
       [2, 3, 4],
       [1, 2, 3],
       [2, 3, 4]])

In [13]:
s4 = s3.reshape((12,))
print(s4)
s5 = s3.reshape((1, 12))
print(s5)

[0 2 3 2 3 4 1 2 3 2 3 4]
[[0 2 3 2 3 4 1 2 3 2 3 4]]


In [14]:
# 多维数组展平
print(s3.shape[0] * s3.shape[1])
s3.flatten()

12


array([0, 2, 3, 2, 3, 4, 1, 2, 3, 2, 3, 4])

In [15]:
# 计算
print(s3)
# 广播机制，每个数字都加2 
print(s3 + 2)   
tmp = s3 + 2

[[0 2 3]
 [2 3 4]
 [1 2 3]
 [2 3 4]]
[[2 4 5]
 [4 5 6]
 [3 4 5]
 [4 5 6]]


In [16]:
s3 = s3 / 0
print(s3)

[[nan inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]


C:\Users\labour\AppData\Local\Temp\ipykernel_20708\1073747164.py:1: RuntimeWarning: divide by zero encountered in divide
  s3 = s3 / 0
C:\Users\labour\AppData\Local\Temp\ipykernel_20708\1073747164.py:1: RuntimeWarning: invalid value encountered in divide
  s3 = s3 / 0


In [17]:
s7 = np.arange(0,12).reshape(4, 3)
print(s7)
print(tmp.flatten())
print(tmp + s7)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[2 4 5 4 5 6 3 4 5 4 5 6]
[[ 2  5  7]
 [ 7  9 11]
 [ 9 11 13]
 [13 15 17]]


In [18]:
t9 = np.arange(10)
t9
print(s7 - t9)  # 某一维度上形状一样就可以进行计算

ValueError: operands could not be broadcast together with shapes (4,3) (10,) 

In [19]:
# numpy轴 shape (2, 2, 3)  分别对应0轴 1轴 2轴
t10 = np.arange(10).reshape((2, 5))    # 2表示0轴长度为2，5表示1轴长度为5

In [27]:
# numpy读取数据
# np.loadtxt(frame, dtype = np.float, delimiter = None, skiprows = 0, usecols = None, unpack = False)
# frame文件  dtype数据类型  delimiter 分割的字符串  unpack会实现转置
import numpy as np
us_file_path = "./USvideos0123.csv"
gb_file_path = "./GBvideos0123.csv"
tt1 = np.loadtxt(us_file_path, dtype = "int", delimiter = ",", skiprows = 1)
print(tt1)
tt2 = np.loadtxt(gb_file_path, dtype = "int", delimiter = ",", skiprows = 1)
print(tt2)

[[4394029  320053    5931   46245]
 [7860119  185853   26679       0]
 [5845909  576597   39774  170708]
 ...
 [ 142908    7088      68     437]
 [  24532    2148      77       0]
 [ 144039    1574      59       0]]
[[7426393   78240   13548     705]
 [ 494203    2651    1309       0]
 [ 142819   13119     151    1141]
 ...
 [ 170003    6592     127     454]
 [ 893125   44811     652    2056]
 [1474925   58532    3223   14396]]


In [31]:
# numpy中的转置
t2 = np.arange(24).reshape((4, 6))
print(t2)
print(t2.transpose())
print(t2.T)
print(t2.swapaxes(1, 0))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [44]:
# numpy的索引和切片 与列表十分类似
print(tt2)
# 取行
print(tt2[2])
# 取连续多行
print(tt2[2:])
# 取不连续多行
print(tt2[[2, 8, 10]])

print("---------------------------------列操作---------------------------------")

# 取列操作
# 取单列
print(tt2)
print(tt2[:, 0])
# 取连续多列
print(tt2[:, 2:])
# 取不连续多列
print(tt2[:, [0, 2]])
# 取行和列 取第3行 第4列的值
print(tt2[2, 3])
# 取多行和多列 取第3行到第5行，第2列到第4列的结果
# 取的是行和列交叉点的位置
print(tt2[2:5, 1:4])
# 取多个不相邻的点 选出来的结果是（0,0）、(2,1)、(2,3)
print(tt2[[0, 2, 2], [0, 1, 3]])

[[7426393   78240   13548     705]
 [ 494203    2651    1309       0]
 [ 142819   13119     151    1141]
 ...
 [ 170003    6592     127     454]
 [ 893125   44811     652    2056]
 [1474925   58532    3223   14396]]
[142819  13119    151   1141]
[[ 142819   13119     151    1141]
 [1580028   65729    1529    3598]
 [  40592    5019      57     490]
 ...
 [ 170003    6592     127     454]
 [ 893125   44811     652    2056]
 [1474925   58532    3223   14396]]
[[ 142819   13119     151    1141]
 [  65453    2761      33     223]
 [1121715   65988     591   51025]]
---------------------------------列操作---------------------------------
[[7426393   78240   13548     705]
 [ 494203    2651    1309       0]
 [ 142819   13119     151    1141]
 ...
 [ 170003    6592     127     454]
 [ 893125   44811     652    2056]
 [1474925   58532    3223   14396]]
[7426393  494203  142819 ...  170003  893125 1474925]
[[13548   705]
 [ 1309     0]
 [  151  1141]
 ...
 [  127   454]
 [  652  2056]
 [ 3223 1439

In [53]:
# numpy中数值的修改
tt3 = np.arange(24).reshape((4, 6))
print(tt3)
# 修改操作
tt3[:, 2:4] = 10
print(tt3)
# 如何将tt3中小于10的数赋值为3
print(tt3 < 10)
tt3[tt3 < 10] = 3
print(tt3)
# tt3中小于10的数字替换乘0，把大于20的数字替换成20
tt4 = np.where(tt3 < 10, 0, 20)
print(tt4)

print(tt3)
# numpy中的clip 将小于10的数替换成10，将大于18的数替换成18
print(tt3.clip(10, 18))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1 10 10  4  5]
 [ 6  7 10 10 10 11]
 [12 13 10 10 16 17]
 [18 19 10 10 22 23]]
[[ True  True False False  True  True]
 [ True  True False False False False]
 [False False False False False False]
 [False False False False False False]]
[[ 3  3 10 10  3  3]
 [ 3  3 10 10 10 11]
 [12 13 10 10 16 17]
 [18 19 10 10 22 23]]
[[ 0  0 20 20  0  0]
 [ 0  0 20 20 20 20]
 [20 20 20 20 20 20]
 [20 20 20 20 20 20]]
[[ 3  3 10 10  3  3]
 [ 3  3 10 10 10 11]
 [12 13 10 10 16 17]
 [18 19 10 10 22 23]]
[[10 10 10 10 10 10]
 [10 10 10 10 10 11]
 [12 13 10 10 16 17]
 [18 18 10 10 18 18]]


In [65]:
# numpy中的nan和inf
# nan: not a number
# inf: infinity 

# 一、两个nan是不相等的
print(np.nan == np.nan)
print(np.nan != np.nan)
# 二、判断数组中nan的个数
tt3 = tt3.astype("float")
tt3[:,2] = np.nan
print(tt3)
print(np.count_nonzero(tt3 != tt3))
# 三、把nan替换为0
tt3[np.isnan(tt3)] = 0
print(tt3)
# 四、nan与任何值计算都为nan

np.sum(tt3, axis = 1)

# 如果将nan全部替换为0，如果替换之前平均值大于0，替换之后均值会变小，一般方法是将缺失的值替换为均值或者中值

False
True
[[ 3.  3. nan 10.  3.  3.]
 [ 3.  3. nan 10. 10. 11.]
 [12. 13. nan 10. 16. 17.]
 [18. 19. nan 10. 22. 23.]]
4
[[ 3.  3.  0. 10.  3.  3.]
 [ 3.  3.  0. 10. 10. 11.]
 [12. 13.  0. 10. 16. 17.]
 [18. 19.  0. 10. 22. 23.]]


array([22., 37., 68., 92.])

In [70]:
# numpy中的常见统计函数
print(tt3)
# 求和
print(np.sum(tt3, axis = 0))
# 均值
print(tt3.mean(axis = 0))
print(np.median(tt3, axis = 0))
# 求最大值
print(tt3.max(axis = 0))
# 求最小值
print(tt3.min(axis = 0))
# 求极差 最大值和最小值之差
print(np.ptp(tt3, axis = 0))
# t.std(axis = none)
# 默认返回多维数组全部的统计结果 指定轴则返回轴上的


[[ 3.  3.  0. 10.  3.  3.]
 [ 3.  3.  0. 10. 10. 11.]
 [12. 13.  0. 10. 16. 17.]
 [18. 19.  0. 10. 22. 23.]]
[36. 38.  0. 40. 51. 54.]
[ 9.    9.5   0.   10.   12.75 13.5 ]
[ 7.5  8.   0.  10.  13.  14. ]
[18. 19.  0. 10. 22. 23.]
[ 3.  3.  0. 10.  3.  3.]
[15. 16.  0.  0. 19. 20.]


In [3]:
import numpy as np
t1 = np.arange(12).reshape((3, 4)).astype("float")
print(t1)
t1[1, 2:] = np.nan
print(t1)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[ 0.  1.  2.  3.]
 [ 4.  5. nan nan]
 [ 8.  9. 10. 11.]]


In [4]:
# 数组的拼接
t1 = np.arange(12).reshape((2, 6))
print(t1)
t2 = np.arange(12,24).reshape((2, 6))
print(t2)
# 竖直拼接
print(np.vstack((t1, t2)))
# 水平拼接
print(np.hstack((t1, t2))) 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]


In [5]:
# 数组的行列交换
t = np.arange(12, 24).reshape((3, 4))
print(t)
# 行进行交换
t[[1, 2],:] = t[[2, 1],:]
print(t)
# 列进行交换
t[:, [0, 2]] = t[:, [2, 0]]
print(t)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15]
 [20 21 22 23]
 [16 17 18 19]]
[[14 13 12 15]
 [22 21 20 23]
 [18 17 16 19]]
